name: Rust checks

on: [push, pull_request]

jobs:
  clippy_check:
    # clippy and rustfmt (stable) already included
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  
  rustfmt_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check